In [2]:
import torch
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

In [4]:
cash_path = '../data/tow-ids-dataset/processed/train_tow-ids.pt'
cache = torch.load(cash_path, weights_only=False)
values, labels = cache['values'], cache['labels']

In [ ]:
labels['timestamp'] = labels['timestamp'].astype(float)
labels['timestamp'] = pd.to_datetime(labels['timestamp'], unit='s')

In [9]:
freq = labels.set_index('timestamp').resample('1S').size().reset_index(name='freq')

fig = px.line(freq, x='timestamp', y='freq',
              title="Frequência de Pacotes por Segundo",
              labels={'timestamp': 'Tempo', 'freq': 'Número de Pacotes'})

fig.show()

/var/folders/fs/f8qz96w55l1cqqbyb70x11380000gn/T/ipykernel_58923/1494767686.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  freq = labels.set_index('timestamp').resample('1S').size().reset_index(name='freq')

In [10]:
labels.head()

    pkt_idx   class   label                     timestamp protocol
27       28  Normal  Normal 2020-09-12 09:51:04.776915073   IP_UDP
28       29  Normal  Normal 2020-09-12 09:51:04.777198076   IP_UDP
29       30  Normal  Normal 2020-09-12 09:51:04.777461052   IP_UDP
30       31  Normal  Normal 2020-09-12 09:51:04.777700901   IP_UDP
31       32  Normal  Normal 2020-09-12 09:51:04.778279066   IP_UDP

In [14]:
labels.reset_index()[labels.reset_index()['label'] != 'Normal'].head()

,index,pkt_idx,class,label,timestamp,protocol
102371,140310,140311,Abnormal,CAN DoS,2020-09-12 09:52:23.861867905,IP_UDP
102373,140312,140313,Abnormal,CAN DoS,2020-09-12 09:52:23.862345934,IP_UDP
102375,140314,140315,Abnormal,CAN DoS,2020-09-12 09:52:23.862976074,IP_UDP
102377,140316,140317,Abnormal,CAN DoS,2020-09-12 09:52:23.863636971,IP_UDP
102379,140318,140319,Abnormal,CAN DoS,2020-09-12 09:52:23.864099979,IP_UDP

In [4]:
cash_path = '../data/autoeth-intrusion-dataset/processed/train_AEID_58.pt'
cache = torch.load(cash_path, weights_only=False)
values, labels = cache['values'], cache['labels']

In [7]:
labels['timestamp'] = labels['pkt_idx'].astype(float)
labels['timestamp'] = pd.to_datetime(labels['timestamp'], unit='s')

In [8]:
freq = labels.set_index('timestamp').resample('1S').size().reset_index(name='freq')

fig = px.line(freq, x='timestamp', y='freq',
              title="Frequência de Pacotes por Segundo",
              labels={'timestamp': 'Tempo', 'freq': 'Número de Pacotes'})

fig.show()

/var/folders/fs/f8qz96w55l1cqqbyb70x11380000gn/T/ipykernel_55622/1494767686.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  freq = labels.set_index('timestamp').resample('1S').size().reset_index(name='freq')